### ISSUE TITLE
Elementary mark on WiFi after connection 

### ISSUE THREAD

**Issue by swap9391** [ThanosFisherman/WifiUtils#104]
When i tried to connect i got Elementary mark on Wifi icon of status bar, that restrict me to proceed further using any internet dependant task.

**Comment by ThanosFisherman** [comment]
For Android versions 10 and newer:* WiFiUtils is currently using the *Network request API* (IoT API) for connecting to wifi networks which scopes the internet connectivity only to the app that requested it. There are plans to support WiFI Suggestion API in the future which overcomes this issue. For further info read the official docs [here](https://developer.android.com/guide/topics/connectivity/wifi-infrastructure) and take a look at the discussion thread [here](https://github.com/ThanosFisherman/WifiUtils/issues/47)
