### ISSUE TITLE
Publish WifiUtils on  Maven Central

### ISSUE THREAD

**Issue by eliaslecomte** [ThanosFisherman/WifiUtils#115]
jCenter is sunsetting soon. Have steps been taken to publish this repo on Maven Central?

**Comment by ThanosFisherman** [comment]
Hey Elias,

It's already in the works :) I just need to find some extra time to deal with some nasty Gradle bugs I ran into.

**Comment by ThanosFisherman** [comment]
And we are up and running on maven central :D
