### ISSUE TITLE
Android 10 not working

### ISSUE THREAD

**Issue by s0641** [ThanosFisherman/WifiUtils#121]
I imported this dependency
dependencies {
       implementation("io.github.thanosfisherman.wifiutils:wifiutils:1.6.6")
    }
    
then I used this
WifiUtils.withContext(getApplicationContext()).enableWifi();

But when I am running It is showing that wifi is enabled but it is not happening in my device.
Please tell me

**Comment by ThanosFisherman** [comment]
Addressed in https://github.com/ThanosFisherman/WifiUtils/pull/124
