### ISSUE TITLE
can you support proxy connect to some wifi?

### ISSUE THREAD

**Issue by hhhaiai** [ThanosFisherman/WifiUtils#19]
can you support proxy connect to some wifi?

**Comment by ThanosFisherman** [comment]
This is not in the to-do list at the moment but if there is high demand then I could investigate it.

I'm also open to contributions btw.

**Comment by hhhaiai** [comment]
> 。

是否可以提供思路。android 8以下我已经可以使用。8和以上的不能用

**Comment by hhhaiai** [comment]
can you show the method.  blow the android 8, already can use proxy. 8 androd above has no idea.

**Comment by ThanosFisherman** [comment]
This library does not support connecting to WiFis with a proxy out of the box.

I am not even sure how you do it below Android 8 as you say, but I have no idea as well.

I may look into it at some point in the future though.

**Comment by hhhaiai** [comment]
> This library does not support connecting to WiFis with a proxy out of the box.
> 
> I am not even sure how you do it below Android 8 as you say, but I have no idea as well.
> 
> I may look into it at some point in the future though.

okey..
