### ISSUE TITLE
Is there any method to check the current connected WiFi SSID ?

### ISSUE THREAD

**Issue by moosabaloch** [ThanosFisherman/WifiUtils#20]
Is there any method to check the current connected WiFi SSID ?

**Comment by ThanosFisherman** [comment]
Hi,
No currently there is not because that's a job of WifiManager anyway but I could add a convenient method for this I suppose.

**Comment by Onkarn92** [comment]
+1 for this

**Comment by IT-Talon** [comment]
And so?

**Comment by ThanosFisherman** [comment]
resolved by #70
