### ISSUE TITLE
mWifiManager.startScan() returns false

### ISSUE THREAD

**Issue by rschlund** [ThanosFisherman/WifiUtils#29]
This call in WifiUtils.java line 88 returns true, when i load WifiUtils from Github and run:

    private void connectWithWpa() {
        WifiUtils.withContext(getApplicationContext()).scanWifi(this::getScanResults).start();
    }

    private void getScanResults(@NonNull final List<ScanResult> results)
    {
        if (results.isEmpty())
        {
            return;
        }
    }

When I run the same code in my project using WifiUtils as library it returns false, so i never get any scanresults.

**Comment by ThanosFisherman** [comment]
Hello,
Make sure your location services are turned on as far as I know this a known issue which occurs when GPS/Location data are disabled.
https://issuetracker.google.com/issues/37060483

There's also been a discussion on this thread https://github.com/ThanosFisherman/WifiUtils/issues/21
