### ISSUE TITLE
Is it possible to add and connect a Wifi network when targeting Android Q? 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ThanosFisherman/WifiUtils#31]
Seems it's not possible anymore:
https://stackoverflow.com/q/56905956/878126
https://issuetracker.google.com/issues/130542363

Is it true?
Is there at least a solution for rooted devices?

**Comment by ThanosFisherman** [comment]
Thanks for the links. I haven't tested this library on Android Q but reading up on the links it seems that it introduces API changes that won't really help address the auto connect feature.

I'm afraid this library won't work as intended on Android Q but I'm willing to try a few workarounds as soon as I get an Android Q device in my hands.

**Comment by AndroidDeveloperLB** [comment]
Do you know of a way to add a network on a rooted device, perhaps?
A way that should work even on Android Q ?
The new API seems to only suggest to add the networks. I've noticed a notification that appears when I do it, but it appears after quite a while, and on some cases doesn't appear at all.

You can try the new API already , on an emulator. Sure it's not the same, but it's a start...
You can see my attempt to add a network using this API here:

https://issuetracker.google.com/issues/136787275

I don't get why it doesn't do anything. I think it's a bug, or that I didn't set it right. Sadly there is no tutorial that I've found, no sample, and barely any documentation...

**Comment by ThanosFisherman** [comment]
I think there should be a way to do it on a rooted device by utilizing commands from wpa_cli file but I haven't look into it.

Regarding the new API I also think it is a bug. I will try to run your code when I find some time.

**Comment by AndroidDeveloperLB** [comment]
Yes, please investigate it. I hope you will find a way to add a network, even if it requires root...

**Comment by ThanosFisherman** [comment]
Refer to #47
