### ISSUE TITLE
WifiManager.saveConfiguration() returns false >= API 26

### ISSUE THREAD

**Issue by zacwolfe** [ThanosFisherman/WifiUtils#39]
This method was deprecated in API 26 and always returns false, causing ConnectorUtils.connectToWifi() to fail. Please remove this call as it is no longer necessary.  Thanks!

**Comment by ThanosFisherman** [comment]
If you look at the android source code this method always returns true therefore it doesn't affect the connection flow. I will keep this for backwards compatibility issues.
