### ISSUE TITLE
Error when i try compile 

### ISSUE THREAD

**Issue by vsarnataro** [ThanosFisherman/WifiUtils#4]
![screenshot 1](https://user-images.githubusercontent.com/11519353/35435731-15bcdcce-028c-11e8-9aff-a21485b9ed20.png)

**Comment by ThanosFisherman** [comment]
I don't know what you are trying to do but this error is not related to this lib. Plus I see some kotlin classes in there. I'm not using kotlin in this library.

**Comment by vsarnataro** [comment]
I use java lib without problems in my kotlin project so I don't think is kotlin problems

**Comment by ThanosFisherman** [comment]
@vsarnataro You probably need to add the following in your app level build.gradle file:
```groovy
android {
 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```
Then try cleaning and Rebuilding the project. Also it would be a good idea to update your kotlin dependency and AndroidStudio kotlin-plugin to latest (`1.2.21`)
