### ISSUE TITLE
@aparecidoSilvano @ThanosFisherman Can refer to this：https://blog.csdn.net/u014632228/article/details/101207983

### ISSUE THREAD

**Issue by atiirajaee** [ThanosFisherman/WifiUtils#41]
@aparecidoSilvano @ThanosFisherman Can refer to this：https://blog.csdn.net/u014632228/article/details/101207983

_Originally posted by @oy-paddy in https://github.com/ThanosFisherman/WifiUtils/issues/38#issuecomment-534014658_

I can't understand the language is Chinese!!!

**Comment by ThanosFisherman** [comment]
Please do not open new issues that already exist.
