### ISSUE TITLE
Disconnect from connected network without disabling Wi-Fi?

### ISSUE THREAD

**Issue by fartem** [ThanosFisherman/WifiUtils#50]
How can I disconnect from a connected network without disabling Wi-Fi?

Right now I'm disconnecting with default SDK methods:

```java
WifiManager wifiManager = (WifiManager) getApplicationContext().getSystemService(
    Context.WIFI_SERVICE
);
wifiManager.disconnect();
```

**Comment by NizarETH** [comment]
me too I do the same :/

**Comment by fartem** [comment]
+ `wifiManager.disconnect();` not working on Android Q.

**Comment by CloseFile** [comment]
I use a trick in my app. When you need to disconnect just enter the wrong password and reconnect

**Comment by ThanosFisherman** [comment]
Future versions will include a disconnect feature. For now use the workaround mentioned by @CloseFile  above or the standard  `wifiManager.disconnect()`

**Comment by fartem** [comment]
@ThanosFisherman thanks!
