### ISSUE TITLE
scan stop immediately

### ISSUE THREAD

**Issue by juicycool92** [ThanosFisherman/WifiUtils#51]
Basicly, most of phone can scan wifi's normally.

but some of phone get COULDN'T SCAN error and stop scam immediately.
i cannot find any solution, i cannot gathering detail log. i stuck at here..

```
D/WifiUtils: WifiUtils: WIFI ENABLED...
D/WifiUtils: WifiUtils: START SCANNING....
I/ROCATEER_LOG - (WifiSelectActivity.java:140) [getScanResults]: SCAN RESULTS IT'S EMPTY
D/WifiUtils: WifiUtils: ERROR COULDN'T SCAN
```

is there any solution or hint for this error?

**Comment by bverhoeven** [comment]
If you're using Android 9 or higher, you're probaby seeing the same issue as in #55:
 
> Each foreground app can scan four times in a 2-minute period.

Attempts to scan more than four times in a 2-minute period will result in an empty list (which will indeed "finish" instantly). There's unfortunately no way to work around these restrictions.

**Comment by juicycool92** [comment]
> If you're using Android 9 or higher, you're probaby seeing the same issue as in #55:
> 
> > Each foreground app can scan four times in a 2-minute period.
> 
> Attempts to scan more than four times in a 2-minute period will result in an empty list (which will indeed "finish" instantly). There's unfortunately no way to work around these restrictions.

Thanks for letting me know current state of problem.
seems like i cant do anything until something update or else.
i close this issue case because duplicated #55
