### ISSUE TITLE
In a few times, Scan Results are empty

### ISSUE THREAD

**Issue by JavaDeveloper08** [ThanosFisherman/WifiUtils#55]
Hi, Thank you very much for your effort, this library is very useful.

But sometimes I am facing a problem. At first, wifi scan result list is greater than 0. And I am trying 
second, third... everything is OK. but when I do fourth try I am getting error below 

WifiUtils: START SCANNING....
I/Result: SCAN RESULTS IT'S EMPTY
D/WifiUtils: WifiUtils: ERROR COULDN'T SCAN

After that, whenever I try to bring scan results, list size is 0. But If I load my fragment again, scan results are running well. 

So, why sometimes scan results are empty ? 

GPS is always open. 

Would you help me?

I am using scanWifi() method in a Fragment. 

private void scanWifi() {
            if(getContext()!=null)
                      WifiUtils.withContext(getContext()).scanWifi(this::getScanResults).start();
    }

private void getScanResults(@NonNull final List<ScanResult> results) {
        if (results.isEmpty()) {
            Log.i("Result", "SCAN RESULTS IT'S EMPTY");
            SnackBarMessageUtil.showErrorMessageWithAction(view, "RESULT IS EMPTY")
                    .setAction("TRY AGAIN", view -> scanWifi()).setActionTextColor(Color.WHITE)
                    .show();
            return;
        }
        Log.i("Result", "GOT SCAN RESULTS " + results);
        SnackBarMessageUtil.showSuccessMessage(view, "RESULT IS SUCCESSFUL");
    }

**Comment by Jasperben** [comment]
I've also found this problem

**Comment by Jasperben** [comment]
I've also found this problem

Android 9

**Comment by bverhoeven** [comment]
This is by design and the expected behavior. Please review:  https://developer.android.com/guide/topics/connectivity/wifi-scan#wifi-scan-throttling

Notably for Android 9 and up:

> Each foreground app can scan four times in a 2-minute period. 

Attempts to scan more often will result in an empty list.

**Comment by JavaDeveloper08** [comment]
@bverhoeven  thank you very much for your reply.
