### ISSUE TITLE
connectWith Wifi no longer working in 1.6.0

### ISSUE THREAD

**Issue by gadget-man** [ThanosFisherman/WifiUtils#64]
I've updated to test 1.6.0, but the following command which was fine in 1.5.1 is no longer able to build:
`WifiUtils.withContext(mContext).connectWith(sSID.trim(), password.trim()).setTimeout(15000).onConnectionResult {isSuccess ->
            mIsWifiConnected = isSuccess
            LoggerUtils.logMessage("Connected Status :$mIsWifiConnected")
            if (mIsWifiConnected) {
                bindToNetwork(mContext)
            }
            wifiConnector.onWifiConnected()
        }.start()`

Type mismatch: inferred type is (???) -> Unit but ConnectionSuccessListener? was expected

**Comment by ThanosFisherman** [comment]
Yeah there are breaking changes in 1.6.0 

`onConnectionResult` now accepts a `ConnectionSuccessListener` interface as a parameter. Have a look at [MainActivity](https://github.com/ThanosFisherman/WifiUtils/blob/445ae419b8c45d5852912ce8c30f55d39b9ee867/sample/src/main/java/com/thanosfisherman/wifiutils/sample/MainActivity.java#L49) to see how this works.

**Comment by gadget-man** [comment]
I noticed that, but can't get the example you pointed to to work in Kotlin, which translates to:

`WifiUtils.withContext(mContext)
            .connectWith(sSID.trim(), password.trim())
            .setTimeout(15000)
            .onConnectionResult(object : ConnectionSuccessListener {
                fun success() {
                    Toast.makeText(mContext, "SUCCESS!", Toast.LENGTH_SHORT).show()
                }

                fun failed(errorCode: ConnectionErrorCode) {
                    Toast.makeText(
                        mContext,
                        "EPIC FAIL!" + errorCode.toString(),
                        Toast.LENGTH_SHORT
                    ).show()
                }
            })
            .start()`

And this won't build. Also, ConnectionErrorCode doesn't seem to be available in com.thanosfisherman.wifiutils.wifiConnect (it shows red)

**Comment by gadget-man** [comment]
I also tried this:
`WifiUtils.withContext(mContext).connectWith(sSID.trim(), password.trim()).setTimeout(15000).onConnectionResult(
            object: ConnectionSuccessListener {
                override fun isSuccessful(isSuccess: Boolean) {
                    TODO("Not yet implemented")
                    LoggerUtils.logMessage("PMN onSuccessListener")
                }
            }).start()`

But get `Object is not abstract and does not implement abstract member public abstract fun failed(@NonNull p0: ConnectionErrorCode): Unit defined in com.thanosfisherman.wifiutils.wifiConnect.ConnectionSuccessListener`

**Comment by ThanosFisherman** [comment]
I see some syntactical errors in your code.

I updated the sample app by including [MainKotlinActivity](https://github.com/ThanosFisherman/WifiUtils/blob/master/sample/src/main/java/com/thanosfisherman/wifiutils/sample/MainKotlinActivity.kt) class to demonstrate usage of the lib in Kotlin.

Check it out and let me know if you still get errors

**Comment by gadget-man** [comment]
Thank you. Not sure what I'd done but this part is working now.
