### ISSUE TITLE
 Exception from call site #14 bootstrap method

### ISSUE THREAD

**Issue by mrgogomaster** [ThanosFisherman/WifiUtils#67]
at com.thanosfisherman.wifiutils.WifiUtils.start(WifiUtils.java:334)
<img width="1646" alt="Screenshot 2020-05-19 at 12 24 56 AM" src="https://user-images.githubusercontent.com/23306263/82249387-4ebe5880-9967-11ea-8206-924cba15edda.png">

**Comment by ThanosFisherman** [comment]
try adding the following in your app level build.gradle file and let me know.

```groovy
android {
   compileOptions {
       sourceCompatibility JavaVersion.VERSION_1_8
       targetCompatibility JavaVersion.VERSION_1_8
   }
}
```

**Comment by mrgogomaster** [comment]
Thanks bro..resolved the issue.
