### ISSUE TITLE
Suggestion: Allow users to forward logs

### ISSUE THREAD

**Issue by asantana48** [ThanosFisherman/WifiUtils#74]
Hi, I was wondering if you would be interested in including the ability to forward logs to other loggers. I'm a fan of using [Timber](https://github.com/JakeWharton/timber) to log things because it, in turn, allows me to forward logs to remote services like PaperTrail and Crashlytics. It would really help me out to see the logs of your library remotely.

This would indirectly help with the core functionality of the project as as well since the whole reason I want to do this is that one of my testers is running into an issue on a Huawei Phone (Android 10, EMUI 10.1.0). If I figure out a fix for his phone I will be sure to open a pull request.

I've already written the code to do this, just let me know if you're interested so I can open a PR.

**Comment by ThanosFisherman** [comment]
Hello @asantana48 Your idea is great! Currently the logging mechanism in WifiUtils is pretty old and could certainly use some upgrades. I also use Timber on my recent projects and it really helps in that regard.

I will be happy to review your pull request :)

**Comment by asantana48** [comment]
Awesome, thanks! Just opened one!

**Comment by ThanosFisherman** [comment]
resolved in #75
