### ISSUE TITLE
BUG: WifiUtils scanWifi scanResults null data

### ISSUE THREAD

**Issue by adaonder** [ThanosFisherman/WifiUtils#80]
Hi, 
 if GPS is on, the result(scanResults) comes. If GPS is off, there is no result. Why was the GPS condition added?

![Screen Shot 2020-08-06 at 08 40 33](https://user-images.githubusercontent.com/25998206/89495224-80a1c700-d7c0-11ea-930d-e03fa231e19d.png)

**Code:**
WifiUtils.withContext(Application.getInstance()).scanWifi(scanResults -> {
                LogUtil.d("scanResults: " + scanResults.size());
...

**Comment by ThanosFisherman** [comment]
Yes we've been through this multiple times. It's a requirement by the Android framework to keep your location data on if you want to scan for wifi networks.

More info [here](https://issuetracker.google.com/issues/37060483)
