### ISSUE TITLE
how to set priority the wifi to connect?

### ISSUE THREAD

**Issue by kailaisi** [ThanosFisherman/WifiUtils#84]
the signal of the WIFI to connected  is weak, often automatically switched. Is there any methods to set the priority of the wifi?

**Comment by ThanosFisherman** [comment]
Shifting priorities is deprecated as of API 26. On pre 26 WifiUtils already assigns the maximum priority to the specified network (see [here](https://github.com/ThanosFisherman/WifiUtils/blob/1c480b24d3eef24caae8aa58dc00d370db0c5ffc/wifiutils/src/main/java/com/thanosfisherman/wifiutils/ConnectorUtils.java#L126)) but there are still not guarantees that the priority will not change again by the OS itself.
