### ISSUE TITLE
Cannot resolve symbol elvis

### ISSUE THREAD

**Issue by eliaslecomte** [ThanosFisherman/WifiUtils#86]
Android apps that still use Gradle dsl can't resolve symbol elvis.
This is a dependency of WifiUtils. Not sure how I should fix this.

**Comment by ThanosFisherman** [comment]
This is strange because it seems to resolve fine on my machine. Let me take a look and post back.

**Comment by eliaslecomte** [comment]
I'm also confused. It works correctly in the sample but not in an empty android app with Kotlin as default (bot not kotlin-dsl).

**Comment by ThanosFisherman** [comment]
Oh so you are having issues when you include WifiUtils dependency on a third party project?

**Comment by eliaslecomte** [comment]
Yes.

**Comment by ThanosFisherman** [comment]
@eliaslecomte I released a new version 1.6.4 let me know if Elvis resolves correctly now. :)

**Comment by eliaslecomte** [comment]
Thanks for the prompt action! It seems to work correctly now. I still had an error but that was due to having both kotlin-stdlib-jdk8 & kotlin-stdlib in my project. Resolved that by switching to kotlin-stdlib-jdk8.

**Comment by ThanosFisherman** [comment]
Kotlin-stdlib supports Java 6 and above. I use kotlin-stdlib-jdk8 in my projects which includes both kotlin-stdlib and kotlin-stdlib-jdk7 as well.

So yeah you only need to include kotlin-stdlib-jdk8 in your project.

Closing this for now.
