### ISSUE TITLE
Get current WiFi ssid

### ISSUE THREAD

**Issue by demiantres** [ThanosFisherman/WifiUtils#90]
Hi,

Is there a method for getting the currently connected SSID (without knowing the SSID beforehand)?

Thanks,

**Comment by asantana48** [comment]
I don't think it's in the library but you could do

WifiManager wifiManager = (WifiManager) context.getApplicationContext().getSystemService(Context.WIFI_SERVICE)
wifiManager.getConnectionInfo().getSSID()
